version: 2
jobs:
  build:
    macos:
      xcode: "8.3.3"
    environment:
      BASH_ENV: "~/.nvm/nvm.sh"
    steps:
      - checkout
      - run:
          name: Install Node 8
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
            source ~/.nvm/nvm.sh
            # https://github.com/creationix/nvm/issues/1394
            set +e
            nvm install 8
      - run:
          name: Update Fastlane
          command: |
            brew update
            brew install ruby
            sudo gem install fastlane
      - run:
          name: Install ImageMagick
          command: |
            brew install imagemagick
      - run:
          name: Install global dependencies
          command: |
            sudo npm install -g cordova coffee-script
      - run:
          name: Install NPM modules
          command: |
            rm -rf node_modules
            npm install
      - run:
          name: Create configuration files
          command: |
            echo 'Bugsnag.apiKey = "YOUR-API-KEY-HERE";' > www/js/bugsnag_apikey.js
            echo 'window.ANDROID_SENDER_ID = "YOUR-ANDROID-ID-HERE";' > www/shared/js/android_sender_id.js
      - run:
          name: Cordova build
          command: |
            rm -rf platforms
            rm -rf plugins
            cordova platform add ios
            # cordova build ios
            # cordova prepare
      - run:
          name: Fastlane
          command: |
            export LC_ALL=en_US.UTF-8
            export LANG=en_US.UTF-8
            fastlane ios build

      # - run:
      #     name: Fastlane Build
      #     no_output_timeout: 1200
      #     command: |
      #       cd platforms/ios
      #       agvtool new-version -all $CIRCLE_BUILD_NUM
            
      #       # if [[ $MATCH_KEYCHAIN_NAME ]]; then
      #       #   fastlane ios release
      #       # else
      #       #   export MATCH_KEYCHAIN_NAME="temp"
      #       #   export MATCH_KEYCHAIN_PASSWORD="temp"
      #       fastlane ios build
      #       # fi