version: 2
jobs:
  build:
    macos:
      xcode: "8.3.3"
    environment:
      BASH_ENV: "~/.nvm/nvm.sh"
    steps:
      - checkout
      - run:
          name: Install Node 8
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
            source ~/.nvm/nvm.sh
            # https://github.com/creationix/nvm/issues/1394
            set +e
            nvm install 8
      - run:
          name: Update Fastlane
          command: |
            brew update
            brew install ruby
            sudo gem install fastlane

      - run:
          name: Install Cordova
          command: |
            sudo npm install -g cordova
      - run:
          name: Install NPM modules
          command: |
            rm -rf node_modules
            npm install
      - run:
          name: Cordova build
          command: |
            cordova platform add ios
            cordova build ios


      # - run:
      #     name: Fastlane Build
      #     no_output_timeout: 1200
      #     command: |
      #       cd platforms/ios
      #       agvtool new-version -all $CIRCLE_BUILD_NUM
            
      #       # if [[ $MATCH_KEYCHAIN_NAME ]]; then
      #       #   fastlane ios release
      #       # else
      #       #   export MATCH_KEYCHAIN_NAME="temp"
      #       #   export MATCH_KEYCHAIN_PASSWORD="temp"
      #       fastlane ios build
      #       # fi